name = "demity-tus-dev"
main = "src/index.ts"
compatibility_date = "2023-05-10"
compatibility_flags = ["nodejs_compat"]
# logpush = true  # requires Enterprise plan
routes = [{ pattern = "dev-uploads.demity.app", custom_domain = true }]

r2_buckets = [
    { binding = "ATTACHMENT_BUCKET", bucket_name = "demity-uploads-dev", preview_bucket_name = "demity-uploads-dev" },
    { binding = "BACKUP_BUCKET", bucket_name = "demity-backups-dev", preview_bucket_name = "demity-backups-dev" }
]

durable_objects.bindings = [
    { name = "ATTACHMENT_UPLOAD_HANDLER", class_name = "AttachmentUploadHandler" },
    { name = "BACKUP_UPLOAD_HANDLER", class_name = "BackupUploadHandler" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["AttachmentUploadHandler", "BackupUploadHandler"]

[vars]
CORS_ORIGINS = "*"

[env.production]
name = "demity-tus"
routes = [{ pattern = "uploads.demity.app", custom_domain = true }]

[env.production.vars]
CORS_ORIGINS = "https://demity.app,https://www.demity.app"

[[env.production.r2_buckets]]
binding = "ATTACHMENT_BUCKET"
bucket_name = "demity-uploads"
preview_bucket_name = "demity-uploads"

[[env.production.r2_buckets]]
binding = "BACKUP_BUCKET"
bucket_name = "demity-backups"
preview_bucket_name = "demity-backups"

[[env.production.durable_objects.bindings]]
name = "ATTACHMENT_UPLOAD_HANDLER"
class_name = "AttachmentUploadHandler"

[[env.production.durable_objects.bindings]]
name = "BACKUP_UPLOAD_HANDLER"
class_name = "BackupUploadHandler"

# To set an auth secret,
# wrangler secret put SHARED_AUTH_SECRET
