name = "demity-tus-dev"
main = "src/index.ts"
compatibility_date = "2023-05-10"
compatibility_flags = ["nodejs_compat"]
logpush = true

r2_buckets = [
    { binding = "ATTACHMENT_BUCKET", bucket_name = "demity-uploads-dev", preview_bucket_name = "demity-uploads-dev" },
    { binding = "BACKUP_BUCKET", bucket_name = "demity-backups-dev", preview_bucket_name = "demity-backups-dev" }
]

durable_objects.bindings = [
    { name = "ATTACHMENT_UPLOAD_HANDLER", class_name = "AttachmentUploadHandler" },
    { name = "BACKUP_UPLOAD_HANDLER", class_name = "BackupUploadHandler" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["AttachmentUploadHandler", "BackupUploadHandler"]

[env.production]
name = "demity-tus"
routes = [{ pattern = "uploads.demity.app", custom_domain = true }]
durable_objects.bindings = [
    { name = "ATTACHMENT_UPLOAD_HANDLER", class_name = "AttachmentUploadHandler" },
    { name = "BACKUP_UPLOAD_HANDLER", class_name = "BackupUploadHandler" }
]
r2_buckets = [
    { binding = "ATTACHMENT_BUCKET", bucket_name = "demity-uploads", preview_bucket_name = "demity-uploads" },
    { binding = "BACKUP_BUCKET", bucket_name = "demity-backups", preview_bucket_name = "demity-backups" }
]

# To set an auth secret,
# wrangler secret put SHARED_AUTH_SECRET
